name: Build Electron App

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macOS-11]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          yarn-version: '1.x'

      - name: Install Dependencies
        run: yarn install

      - name: Make the app
        run: yarn make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DinamicJs-app
          path: out/make
