name: Build Electron App

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macOS-12]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          yarn-version: '1.x'

      - name: Install Dependencies
        run: yarn install

      - name: Publish the app
        run: yarn publish:ef
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DinamicJs-app
          path: out/make
